#!/usr/bin/env bash
# Retrieve information for a specified domain name and its subdomains
if [ $# -lt 1 ]; then
	echo "USAGE : ./0-world_wide_web domain [subdomain]"
fi
if [ $# -eq 1 ]; then
	domainName="$1"
	subdomains=("www" "lb-01" "web-01" "web-02")
	for subdom in "${subdomains[@]}"; do
		res=$(dig "$subdom"."$domainName" +noall +answer)
		record_type=$(echo "$res" | awk '{print $4}')
		ip_address=$(echo "$res" | awk '{print $5}')
		echo "The subdomain $subdom is a $record_type record and points to $ip_address"
	done
fi


if [ $# -gt 1 ]; then
	domainName="$1"
	subdom="$2"
	res=$(dig "$subdom"."$domainName" +noall +answer)
	record_type=$(echo "$res" | awk '{print $4}')
	ip_address=$(echo "$res" | awk '{print $5}')
	echo "The subdomain $subdom is a $record_type record and points to $ip_address"
fi