#!/usr/bin/bash
if  [ $# -eq 0 ]; then
echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
ping $1
fi

listen : nc -l -p <port_number>

sender : nc -l -p <port> < file_to_send
receiver : nc -w 3 <host> <port> > received_file

Port Scanning: nc -zv <host> <start_port>-<end_port>
Chatting:
You can use nc for simple text-based chat between two devices:
On one machine: nc -l -p <port>
On the other machine: nc <host> <port>