#!/usr/bin/env bash
# Script thats install nginx web server
sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo tee /etc/nginx/sites-available/default > /dev/null <<EOF
server {
    listen 80 default_server;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

sudo service nginx restart