#!/usr/bin/env bash

FILE=apache-access.log

if [ -e "$FILE" ]; then
    SORTED_FILE=$(awk '{print $1, $9}' "$FILE" | sort)
    COUNTED_OUTPUT=$(echo "$SORTED_FILE" | uniq -c | sort -rn)
    echo "$COUNTED_OUTPUT"
fi
