#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with the below requirements.
#Requirements:
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.
#The checker is running on Docker, so make sure to read this

cp /etc/hosts ~/hosts-new.tmp
sed -i 's/127.0.0.1\tlocalhost/127.0.0.2\tlocalhost/' ~/hosts-new.tmp
echo -e '8.8.8.8\tfacebook.com' >> ~/hosts-new.tmp
cp -f ~/hosts-new.tmp /etc/hosts
rm ~/hosts-new.tmp
