#!/usr/bin/env bash
#Bash script that displays all active IPv4 IPs on the machine it’s executed on.

ifconfig | grep -E 'inet \b((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b' | awk '{print $2}' 