#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user.
sudo id "nginx" &>/dev/null || sudo useradd -m "nginx"
sudo chmod 755 /run/
sudo touch /run/nginx.pid
sudo chown -R nginx:nginx /etc/nginx /var/log/nginx /run/nginx.pid /usr/sbin/nginx /var/lib/nginx
sudo sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
